---
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- value: Entre las tablas bibliotecas y libros existe una relación 1 a 1
  checked: false
- value: Entre las tablas bibliotecas y libros existe una relación 1 a N
  checked: true
- value: Entre las tablas bibliotecas y libros existe una relación N a N
  checked: false
- value: La clave primaria de la tabla libros es id_biblioteca
  checked: false
- value: La clave primaria de la tabla bibliotecas es id_biblioteca
  checked: true
- value: La tabla libros no tiene clave foránea
  checked: false
- value: La tabla bibliotecas no tiene clave foránea
  checked: true
name: DER
