---
tags: []
layout: input_right
editor: single_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- value: Calcula el total de paquetes de proyectores que se están administrando
  checked: false
- value: Calcula la cantidad de paquetes de proyectores en tránsito
  checked: true
- value: Calcula el promedio del precio de los paquetes de proyectores en la empresa
  checked: false
- value: Ninguna de las anteriores
  checked: false
